import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import dotenv from "dotenv";
import { healthRouter } from "./routes/health";
import { usersRouter } from "./routes/users";
import { adminRouter } from "./routes/admin";
import { errorHandler } from "./middleware/errorHandler";
import { initDb } from "./config/db";

dotenv.config();
const app = express();
const PORT = process.env.PORT || 3001;
app.use(helmet());
app.use(cors());
app.use(morgan("dev"));
app.use(express.json());
app.use("/api/health", healthRouter);
app.use("/api/users", usersRouter);
app.use("/api/admin", adminRouter);
app.use(errorHandler);
initDb().then(() => { app.listen(PORT, () => { console.log(`Backend on port ${PORT}`); }); }).catch((err) => { console.error("DB init failed:", err); process.exit(1); });
export default app;
